# Generated by Django 6.1.1 on 2026-09-30 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_comment'),
        ('core', '0002_recipe_image_url_alter_recipe_status'),
    ]

    operations = [
    ]
