# Generated by Django 6.1.1 on 2026-10-01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_recipe_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="category",
            field=models.CharField(
                choices=[
                    ("breakfast", "Breakfast"),
                    ("lunch", "Lunch"),
                    ("dinner", "Dinner"),
                    ("dessert", "Dessert"),
                    ("snack", "Snack"),
                    ("drink", "Drink"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="recipe",
            name="liked_by",
            field=models.ManyToManyField(
                blank=True,
                related_name="liked_recipes",
                to="auth.user",
            ),
        ),
    ]